# cloudbuild.yaml — build, push, deploy
substitutions:
  _SERVICE: "cityflow"
  _REGION: "europe-west2"

steps:
- name: gcr.io/cloud-builders/docker
  args:
    [
      "build",
      "-t","europe-west2-docker.pkg.dev/$PROJECT_ID/cityflow/$_SERVICE:$SHORT_SHA",
      "-t","europe-west2-docker.pkg.dev/$PROJECT_ID/cityflow/$_SERVICE:latest",
      "."
    ]

- name: gcr.io/cloud-builders/docker
  args: ["push","europe-west2-docker.pkg.dev/$PROJECT_ID/cityflow/$_SERVICE:$SHORT_SHA"]

- name: gcr.io/cloud-builders/docker
  args: ["push","europe-west2-docker.pkg.dev/$PROJECT_ID/cityflow/$_SERVICE:latest"]

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "run","deploy","$_SERVICE",
      "--image","europe-west2-docker.pkg.dev/$PROJECT_ID/cityflow/$_SERVICE:$SHORT_SHA",
      "--region","$_REGION",
      "--platform","managed",
      "--allow-unauthenticated",
      "--port","8080",
      "--timeout","300",
      "--concurrency","1"
    ]

images:
- "europe-west2-docker.pkg.dev/$PROJECT_ID/cityflow/$_SERVICE:$SHORT_SHA"
- "europe-west2-docker.pkg.dev/$PROJECT_ID/cityflow/$_SERVICE:latest"

# (optional) avoid bucket requirement if you set a SA on the trigger
options:
  logging: CLOUD_LOGGING_ONLY