name: Web Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "web/**"
  workflow_dispatch:

permissions:
  id-token: write      # required for OIDC
  contents: read

concurrency:
  group: web-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync web to S3
        run: |
          aws s3 sync web/ s3://${{ vars.WEB_BUCKET_NAME }}/ --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
